name: build_windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup premake
      uses: abel0b/setup-premake@v2.2
      with:
        version: "5.0.0-beta2"
    - name: Generate project files
      run: premake5 vs2019
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Build with msbuild
      run: msbuild Brick-Stacker-OpenGL.sln /p:Configuration=Release
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows
        path: bin\Brick-Stacker-OpenGL\Release-windows-x86_64\