name: build_windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup premake
      uses: abel0b/setup-premake@v2.2
      with:
        version: "5.0.0-beta2"
    - name: Generate project files
      run: premake5 vs2019
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: premake
        path: build/